#### Step1: ตรวจสอบว่า library ของ numpy ถูกติดตั้งอยู่หรือไม่

In [4]:
pip show numpy

Name: numpy
Version: 1.25.2
Summary: Fundamental package for array computing in Python
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD-3-Clause
Location: d:\pythonmlbcel\env\lib\site-packages
Requires: 
Required-by: 
Note: you may need to restart the kernel to use updated packages.


##### Step 2: ติดตั้ง numpy

In [2]:
pip install numpy

You should consider upgrading via the 'd:\PythonMLBCEL\env\Scripts\python.exe -m pip install --upgrade pip' command.


#### Step 3: การสร้างอาเรย์ใน Numpy

In [13]:
import numpy as np

# Scalar Array
a = np.array(10)
print(a)

# Vector Array
row = np.array([1, 2, 3]) # 1 row and 3 columns
col = np.array([[1], [2], [3]]) # 3 rows and 1 column
print(row)
print(col)

# Matrix Array
mat = np.array([[10, 11, 12], [13, 14, 15]]) # 2 rows and 3 columns
print(mat)

10
[1 2 3]
[[1]
 [2]
 [3]]
[[10 11 12]
 [13 14 15]]


#### Step 4: การสร้างตัวเลขสุ่ม

In [119]:
# random เลขทศนิยม 0-1
r1 = np.random.random(4) # สุ่ม vector ขนาด 4 ตัว
r2 = np.random.random([2, 3]) # สุ่ม matrix ขนาด 2x3
print(r1)
print(r2)

# random จำนวนเต็ม
r3 = np.random.randint(0, 11, 6) # สุ่มจำนวนเต็ม 6 ตัว ตั้งแต่ 0-10
r4 = np.random.randint(0, 11, [2, 3]) # สุ่มจำนวนเต็ม 2x3 ตั้งแต่ 0-10
print(r3)
print(r4)

[0.19557896 0.77526368 0.63755977 0.30096787]
[[0.92029568 0.71257023 0.66770062]
 [0.1847231  0.49394212 0.31566612]]
[ 7  1  6  5  0 10]
[[5 5 3]
 [3 3 4]]


#### Step 5: เข้าถึงและเลือกสมาชิกในอาร์เรย์

In [127]:
vrow = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(vrow[3]) # เลือกข้อมูลตำแหน่งที่ 3 จากข้อมูลใน vrow
print(vrow[-1]) # เลือกข้อมูลตำแหน่งที่ 1 จากข้อมูลใน vrow
print(vrow[2:7]) # เลือกข้อมูลตำแหน่งที่ 2 ถึง 6 จากข้อมูลใน vrow
print(vrow[:4]) # เลือกข้อมูลตำแหน่งแรก ถึง 3 จากข้อมูลใน vrow
print(vrow[4:]) # เลือกข้อมูลตำแหน่งที่ 4 ถึงตำแหน่งสุดท้าย จากข้อมูลใน vrow

4
10
[3 4 5 6 7]
[1 2 3 4]
[ 5  6  7  8  9 10]


#### Step 6: การหาค่าทางสถิติของข้อมูลด้วย Numpy

In [136]:
stat = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

print(stat)
# หาค่าสูงสุด (max)
print("Max:", np.max(stat))
# หาค่าต่ำสุด (min)
print("Min:", np.min(stat))
# หาค่าเฉลี่ย (mean)
print("Mean:", np.mean(stat))
# หาค่ามัธยฐาน (median)
print("Median:", np.median(stat))
# หาค่าเบี่ยงเบนมาตรฐาน (std)
print("Std:", np.std(stat))
# หาค่าความแปรปรวน (var)
print("Var:", np.var(stat))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Max: 12
Min: 1
Mean: 6.5
Median: 6.5
Std: 3.452052529534663
Var: 11.916666666666666
